spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wms_test
    username: postgres
    password: 123
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties.hibernate.format_sql: true
  sendgrid:
    api-key:
jwt:
  secret: secret

springdoc:
  api-docs:
    path: /api-docs
